Repository metanet-number1-metabus/metabus, pull requests merged in 2023-05, with the labels that each got.

#2 도커 파일 생성
  Dockerfile
Labels: InProgress

#3 develop -> main 머지
  Dockerfile
Labels: Done

#4 Log4j2 적용 및 에러 코드 핸들러 추가
  build.gradle
  src/main/java/com/metanet/metabus/common/exception/AbstractAppException.java
  src/main/java/com/metanet/metabus/common/exception/ErrorCode.java
  src/main/java/com/metanet/metabus/common/exception/ErrorResponse.java
  src/main/java/com/metanet/metabus/common/exception/GlobalExceptionHandler.java
  src/main/java/com/metanet/metabus/common/exception/bad_request/BadConstantException.java
  src/main/java/com/metanet/metabus/common/exception/bad_request/FileNotExistsException.java
  src/main/java/com/metanet/metabus/common/exception/conflict/DuplicateConfirmedException.java
  src/main/java/com/metanet/metabus/common/exception/conflict/DuplicateEmailException.java
  src/main/java/com/metanet/metabus/common/exception/conflict/DuplicateNicknameException.java
  src/main/java/com/metanet/metabus/common/exception/forbidden/InvalidPermissionException.java
  src/main/java/com/metanet/metabus/common/exception/internal_server_error/DatabaseException.java
  src/main/java/com/metanet/metabus/common/exception/not_found/AlreadyDeletedMemberException.java
  src/main/java/com/metanet/metabus/common/exception/not_found/EmailNotFoundException.java
  src/main/java/com/metanet/metabus/common/exception/not_found/MemberNotFoundException.java
  src/main/java/com/metanet/metabus/common/exception/request_timeout/APIRequestTimeoutException.java
  src/main/java/com/metanet/metabus/common/exception/unauthorized/InvalidFileFormatException.java
  src/main/java/com/metanet/metabus/common/exception/unauthorized/InvalidPasswordException.java
  src/main/java/com/metanet/metabus/common/exception/unauthorized/InvalidTokenException.java
  src/main/java/com/metanet/metabus/common/exception/unauthorized/MemberNotLoggedInException.java
  src/main/resources/log4j2.xml
Labels: InProgress

#5 Auditing 설정 추가 및 BaseEntity 추가
  src/main/java/com/metanet/metabus/common/BaseEntity.java
  src/main/java/com/metanet/metabus/config/JpaAuditingConfiguration.java
Labels: InProgress

#7 시외버스 시간표 조회 기능 구현
  src/main/java/com/metanet/metabus/bus/controller/BusController.java
  src/main/java/com/metanet/metabus/bus/controller/testController.java
  src/main/resources/templates/bus/busTimeTable.html
  src/main/resources/templates/etc/default-init.html
  src/main/resources/templates/fragments/footer2.html
  src/main/resources/templates/fragments/head.html
Labels: InProgress

#6 분실물 게시판 기능
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/java/com/metanet/metabus/board/dto/LostBoardDto.java
  src/main/java/com/metanet/metabus/board/entity/LostBoard.java
  src/main/java/com/metanet/metabus/board/repository/BoardRepository.java
  src/main/java/com/metanet/metabus/board/service/BoardService.java
  src/main/resources/static/css/styles.css
  src/main/resources/templates/board/Message.html
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/board/boardmodify.html
  src/main/resources/templates/board/boardview.html
  src/main/resources/templates/board/boardwrite.html
  src/main/resources/templates/board/tables.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header2.html
Labels: InProgress

#8 보안 관련 설정 추가 및 회원가입 기능 추가
  build.gradle
  src/main/java/com/metanet/metabus/common/BaseEntity.java
  src/main/java/com/metanet/metabus/config/PasswordEncoderConfig.java
  src/main/java/com/metanet/metabus/config/WebMvcConfig.java
  src/main/java/com/metanet/metabus/home/controller/HomeController.java
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/main/java/com/metanet/metabus/member/dto/MemberLoginRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberRegisterRequest.java
  src/main/java/com/metanet/metabus/member/entity/Member.java
  src/main/java/com/metanet/metabus/member/entity/Role.java
  src/main/java/com/metanet/metabus/member/repository/MemberRepository.java
  src/main/java/com/metanet/metabus/member/service/MemberService.java
  src/main/java/com/metanet/metabus/security/SecurityConfig.java
  src/main/java/com/metanet/metabus/security/config/SecurityConfig.java
  src/main/java/com/metanet/metabus/security/entrypoint/CustomAccessDeniedEntryPoint.java
  src/main/java/com/metanet/metabus/security/entrypoint/CustomAuthenticationEntryPoint.java
  src/main/java/com/metanet/metabus/user/dto/testDto.java
  src/main/java/com/metanet/metabus/user/entity/testEntity.java
  src/main/java/com/metanet/metabus/user/repository/testRepository.java
  src/main/java/com/metanet/metabus/user/service/testService.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/log/register.html
Labels: InProgress

#11 기존 UI 탬플릿 튜닝
  src/main/resources/static/assets/img/METABUS_Logo_W.png
  src/main/resources/static/assets/img/main-1.jpeg
  src/main/resources/static/assets/img/main-2.jpeg
  src/main/resources/static/assets/img/main-3.jpeg
  src/main/resources/static/assets/img/main-4.jpeg
  src/main/resources/static/assets/img/main-5.jpeg
  src/main/resources/static/css/owl.carousel.min.css
  src/main/resources/static/css/style-board.css
  src/main/resources/templates/bus/busTimeTable.html
  src/main/resources/templates/fragments/footer2.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/header2.html
  src/main/resources/templates/layout/default_layout.html
  src/main/resources/templates/main/index.html
Labels: InProgress

#9 좌석 정보를 리턴하는 RestController 구현
  src/main/java/com/metanet/metabus/bus/controller/BusController.java
  src/main/java/com/metanet/metabus/bus/controller/SeatRestController.java
  src/main/java/com/metanet/metabus/bus/dto/testDto.java
  src/main/java/com/metanet/metabus/bus/entity/Bus.java
  src/main/java/com/metanet/metabus/bus/entity/Reservation.java
  src/main/java/com/metanet/metabus/bus/entity/Seat.java
  src/main/java/com/metanet/metabus/bus/entity/testEntity.java
  src/main/java/com/metanet/metabus/bus/repository/BusRepository.java
  src/main/java/com/metanet/metabus/bus/repository/SeatRepository.java
  src/main/java/com/metanet/metabus/bus/repository/testRepository.java
  src/main/java/com/metanet/metabus/bus/service/SeatService.java
  src/main/java/com/metanet/metabus/bus/service/testService.java
  src/main/resources/templates/bus/busTimeTable.html
Labels: InProgress

#13 출발지, 도착지, 출발일, 왕복여부 return 기능 구현
  src/main/java/com/metanet/metabus/bus/controller/BusController.java
Labels: InProgress

#12 채팅관련기능
  build.gradle
  src/main/java/com/metanet/metabus/board/dto/LostBoardDto.java
  src/main/java/com/metanet/metabus/bus/service/BusService.java
  src/main/java/com/metanet/metabus/chat/WebSocketConfig.java
  src/main/java/com/metanet/metabus/chat/controller/ChatController.java
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/chat/controller/RoomForm.java
  src/main/java/com/metanet/metabus/chat/dto/ChatDto.java
  src/main/java/com/metanet/metabus/chat/dto/ChatMessage.java
  src/main/java/com/metanet/metabus/chat/dto/RoomDto.java
  src/main/java/com/metanet/metabus/chat/entity/Chat.java
  src/main/java/com/metanet/metabus/chat/entity/Room.java
  src/main/java/com/metanet/metabus/chat/repository/ChatRepository.java
  src/main/java/com/metanet/metabus/chat/repository/RoomRepository.java
  src/main/java/com/metanet/metabus/chat/service/ChatService.java
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/roomList.html
  src/main/resources/templates/fragments/header2.html
Labels: InProgress

#14 [Feat] chat 관련 기능 수정 ui및 서버url , 왼쪽위 metabus로고 클릭시 메인으로 가게 수정 , room …
  src/main/java/com/metanet/metabus/chat/controller/ChatController.java
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/chat/service/ChatService.java
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/roomList.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/header2.html
Labels: InProgress

#16 로그인 기능 추가 및 여러 기능 추가
  build.gradle
  src/main/java/com/metanet/metabus/MetabusApplication.java
  src/main/java/com/metanet/metabus/common/LogAspect.java
  src/main/java/com/metanet/metabus/common/exception/ErrorCode.java
  src/main/java/com/metanet/metabus/common/exception/ErrorResponse.java
  src/main/java/com/metanet/metabus/common/exception/GlobalExceptionHandler.java
  src/main/java/com/metanet/metabus/common/exception/unauthorized/InvalidTokenException.java
  src/main/java/com/metanet/metabus/config/SecurityConfig.java
  src/main/java/com/metanet/metabus/config/WebMvcConfig.java
  src/main/java/com/metanet/metabus/home/controller/HomeController.java
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/main/java/com/metanet/metabus/member/controller/SessionConst.java
  src/main/java/com/metanet/metabus/member/dto/MemberDto.java
  src/main/java/com/metanet/metabus/member/dto/MemberLoginRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberRegisterRequest.java
  src/main/java/com/metanet/metabus/member/entity/Member.java
  src/main/java/com/metanet/metabus/member/entity/Role.java
  src/main/java/com/metanet/metabus/member/service/MemberService.java
  src/main/java/com/metanet/metabus/security/entrypoint/CustomAccessDeniedEntryPoint.java
  src/main/java/com/metanet/metabus/security/entrypoint/CustomAuthenticationEntryPoint.java
  src/main/resources/log4j2.xml
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/log/login.html
  src/main/resources/templates/log/register.html
  src/main/resources/templates/mypage/admin.html
Labels: InProgress

#17 bus 예약 시스템 front-end 개발
  src/main/resources/static/assets/img/file-check-fill.svg
  src/main/resources/static/assets/img/file-excel-fill.svg
  src/main/resources/static/assets/img/file.svg
  src/main/resources/static/css/owl.carousel.min.css
  src/main/resources/templates/bus/busTimeTable.html
  src/main/resources/templates/main/index.html
Labels: InProgress

#18 세션에 id 추가
  src/main/java/com/metanet/metabus/member/service/MemberService.java
Labels: bug
