Repository metanet-number1-metabus/metabus, pull requests merged in 2023-06, with the labels that each got.

#19 버스 예약 기능&페이지 관련 에러들 수정
  src/main/java/com/metanet/metabus/bus/controller/ReservationController.java
  src/main/java/com/metanet/metabus/bus/controller/SeatRestController.java
  src/main/java/com/metanet/metabus/bus/repository/SeatRepository.java
  src/main/java/com/metanet/metabus/bus/service/ReservationService.java
  src/main/java/com/metanet/metabus/bus/service/SeatService.java
  src/main/java/com/metanet/metabus/common/exception/ErrorCode.java
  src/main/java/com/metanet/metabus/common/exception/conflict/DuplicateSeatException.java
  src/main/resources/templates/bus/busTimeTable.html
Labels: InProgress

#20 채팅창 수정 및 게시판 수정
  build.gradle
  src/main/java/com/metanet/metabus/board/config/AwsS3Config.java
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/java/com/metanet/metabus/board/dto/AwsS3.java
  src/main/java/com/metanet/metabus/board/service/AwsS3Service.java
  src/main/java/com/metanet/metabus/board/service/BoardService.java
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/chat/entity/Room.java
  src/main/java/com/metanet/metabus/chat/repository/RoomRepository.java
  src/main/java/com/metanet/metabus/chat/service/ChatService.java
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/board/boardview.html
  src/main/resources/templates/board/boardwrite.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/fragments/header2.html
Labels: InProgress

#21 시큐리티 설정 변경
  src/main/java/com/metanet/metabus/config/SecurityConfig.java
Labels: bug

#22 게시판 다중 이미지 첨부 기능 추가 및 수정 기능
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/java/com/metanet/metabus/board/entity/LostBoard.java
  src/main/java/com/metanet/metabus/board/service/AwsS3Service.java
  src/main/java/com/metanet/metabus/board/service/BoardService.java
  src/main/java/com/metanet/metabus/board/service/ImageUtils.java
  src/main/resources/templates/board/boardmodify.html
  src/main/resources/templates/board/boardwrite.html
Labels: InProgress

#25 bus 예약 시스템 (승차권 보관함 페이지 [bus-reservation-table]) front-end 개발
  src/main/java/com/metanet/metabus/bus/controller/ReservationController.java
  src/main/resources/static/assets/img/testqr.png
  src/main/resources/static/css/datepicker.css
  src/main/resources/static/css/owl.carousel.min.css
  src/main/resources/templates/bus/bus-reservation-table.html
  src/main/resources/templates/bus/busTimeTable.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/main/index.html
Labels: InProgress

#27 board Integer => Long
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/java/com/metanet/metabus/board/dto/LostBoardDto.java
  src/main/java/com/metanet/metabus/board/entity/LostBoard.java
  src/main/java/com/metanet/metabus/board/repository/BoardRepository.java
  src/main/java/com/metanet/metabus/board/repository/testRepository.java
  src/main/java/com/metanet/metabus/board/service/BoardService.java
Labels: InProgress

#28 컨트롤러 수정
  src/main/java/com/metanet/metabus/bus/controller/BusController.java
  src/main/java/com/metanet/metabus/bus/controller/BusRestController.java
  src/main/java/com/metanet/metabus/bus/controller/SeatRestController.java
  src/main/resources/templates/bus/busTimeTable.html
Labels: InProgress

#29 페이지에러처리 조금, boardList paging 로직 변경, 게시판 ui변경,게시판생성시 제목,내용 입력 필수,이미지아닌 파일 올릴때 게시글 안만들어짐
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/java/com/metanet/metabus/board/dto/LostBoardDto.java
  src/main/java/com/metanet/metabus/board/entity/LostBoard.java
  src/main/java/com/metanet/metabus/board/repository/BoardRepository.java
  src/main/java/com/metanet/metabus/board/service/BoardService.java
  src/main/java/com/metanet/metabus/board/service/ImageUtils.java
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/common/exception/ErrorCode.java
  src/main/java/com/metanet/metabus/common/exception/unauthorized/invalidSession.java
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/board/boardmodify.html
  src/main/resources/templates/board/boardview.html
  src/main/resources/templates/board/boardwrite.html
  src/main/resources/templates/chat/room.html
Labels: InProgress

#30 chatroom 완료버튼추가 => 0시 0분 0초 매일 마다 db에 완료상태의 행의 deletedate컬럼이 update됌
  build.gradle
  src/main/java/com/metanet/metabus/MetabusApplication.java
  src/main/java/com/metanet/metabus/chat/component/RoomCleanupScheduler.java
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/chat/dto/RoomDto.java
  src/main/java/com/metanet/metabus/chat/entity/Room.java
  src/main/java/com/metanet/metabus/chat/repository/RoomRepository.java
  src/main/java/com/metanet/metabus/chat/service/ChatService.java
  src/main/resources/templates/bus/busTimeTable.html
  src/main/resources/templates/chat/room.html
Labels: InProgress

#33 예약 조회 기능 구현 및 페이지와 연결
  src/main/java/com/metanet/metabus/bus/controller/BusController.java
  src/main/java/com/metanet/metabus/bus/controller/BusRestController.java
  src/main/java/com/metanet/metabus/bus/dto/ReservationDto.java
  src/main/java/com/metanet/metabus/bus/repository/ReservationRepository.java
  src/main/java/com/metanet/metabus/bus/service/ReservationService.java
  src/main/java/com/metanet/metabus/common/exception/ErrorCode.java
  src/main/java/com/metanet/metabus/common/exception/not_found/SeatNotFoundException.java
  src/main/resources/templates/bus/bus-payment.html
  src/main/resources/templates/bus/bus-reservation-table.html
  src/main/resources/templates/bus/bus-time-table.html
Labels: InProgress

#35 jacoco 설정 수정
  build.gradle
Labels: Done

#36 bus reservation 데이터 종류별 분류
  src/main/java/com/metanet/metabus/bus/controller/BusController.java
  src/main/resources/templates/bus/bus-reservation-table.html
Labels: InProgress

#37 버스 예약: 10분 초과시 자동 delete 기능
  build.gradle
  src/main/java/com/metanet/metabus/bus/repository/ReservationRepository.java
  src/main/java/com/metanet/metabus/bus/scheduler/MyJob.java
  src/main/java/com/metanet/metabus/bus/scheduler/QuartzConfig.java
Labels: InProgress

#38 버스 시간테이블 기능 추가 , 메인페이지 및 채팅방 ui수정
  src/main/resources/static/assets/img/META_Logo.png
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/board/boardmodify.html
  src/main/resources/templates/board/boardview.html
  src/main/resources/templates/board/boardwrite.html
  src/main/resources/templates/bus/bus-time-table.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/main/index.html
Labels: InProgress

#39 버스 결제 기능 마무리
  src/main/java/com/metanet/metabus/bus/controller/BusController.java
  src/main/java/com/metanet/metabus/bus/controller/BusRestController.java
  src/main/java/com/metanet/metabus/bus/entity/Reservation.java
  src/main/java/com/metanet/metabus/bus/repository/ReservationRepository.java
  src/main/java/com/metanet/metabus/bus/service/ReservationService.java
  src/main/java/com/metanet/metabus/bus/service/SeatService.java
  src/main/resources/templates/bus/bus-payment.html
Labels: InProgress

#40 메인페이지 로고변경 및 채팅방 ui개선
  src/main/resources/static/assets/img/busAnimation.gif
  src/main/resources/static/assets/img/busAnimations.gif
  src/main/resources/static/assets/img/testLogo.png
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/board/boardwrite.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/main/index.html
Labels: InProgress

#42 회원가입, 로그인 디자인 변경
  src/main/resources/templates/bus/bus-payment.html
  src/main/resources/templates/log/check_password_info.html
  src/main/resources/templates/log/check_password_pwd.html
  src/main/resources/templates/log/edit_info.html
  src/main/resources/templates/log/edit_oauth.html
  src/main/resources/templates/log/edit_password.html
  src/main/resources/templates/log/login.html
  src/main/resources/templates/log/register.html
  src/main/resources/templates/mypage/mypage.html
Labels: Done

#41 메인 페이지 로고 변경
  src/main/resources/static/assets/img/busAni.gif
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/main/index.html
Labels: InProgress

#46 배포 서버 소켓 stomp 접근권한 허용, room ui 및 기능수정
  src/main/java/com/metanet/metabus/chat/WebSocketConfig.java
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/chat/controller/RoomForm.java
  src/main/resources/static/assets/img/busAni2.gif
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/main/index.html
Labels: InProgress

#48 Oauth2 설정 수정
  src/main/resources/templates/log/login.html
Labels: Done

#50 bus 마일리지페이지, 마이페이지 front-end 개발
  src/main/resources/static/assets/demo/chart-pie-demo.js
  src/main/resources/static/css/style-board.css
  src/main/resources/templates/fragments/footer2.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/mypage/mileage-table.html
  src/main/resources/templates/mypage/mypage.html
Labels: InProgress

#53 myPage ui 변경 및 data db에서 가져오게 설정
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/main/java/com/metanet/metabus/member/entity/Member.java
  src/main/java/com/metanet/metabus/member/repository/MyPageRepository.java
  src/main/java/com/metanet/metabus/member/service/MemberService.java
  src/main/java/com/metanet/metabus/member/service/MyPageService.java
  src/main/resources/templates/mypage/mypage.html
Labels: InProgress

#54 Board 패키지내 test 파일 제거
  src/main/java/com/metanet/metabus/board/controller/testController.java
  src/main/java/com/metanet/metabus/board/dto/testDto.java
  src/main/java/com/metanet/metabus/board/entity/testEntity.java
  src/main/java/com/metanet/metabus/board/repository/testRepository.java
  src/main/java/com/metanet/metabus/board/service/testService.java
Labels: InProgress

#57 bus 결제페이지, 버스 예약조회 페이지 front-end 리모델링
  src/main/java/com/metanet/metabus/bus/controller/BusController.java
  src/main/resources/templates/bus/bus-payment.html
  src/main/resources/templates/bus/bus-reservation-table.html
  src/main/resources/templates/main/index.html
Labels: InProgress

#59 Feature/metabus 48
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/main/java/com/metanet/metabus/member/service/MemberService.java
  src/test/java/com/metanet/metabus/member/controller/MemberControllerTest.java
  src/test/java/com/metanet/metabus/member/service/MemberServiceTest.java
Labels: Done

#60 Feature/metabus 55
  src/main/java/com/metanet/metabus/common/LogAspect.java
  src/test/java/com/metanet/metabus/member/service/MemberServiceTest.java
Labels: Done

#61 Board 및 chat 테스트코드작성
  src/main/java/com/metanet/metabus/board/AwsS3.java
  src/main/java/com/metanet/metabus/board/ImageUtils.java
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/java/com/metanet/metabus/board/dto/AwsS3Dto.java
  src/main/java/com/metanet/metabus/board/dto/LostBoardDto.java
  src/main/java/com/metanet/metabus/board/service/BoardService.java
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/chat/dto/ChatDto.java
  src/main/java/com/metanet/metabus/chat/dto/RoomDto.java
  src/main/java/com/metanet/metabus/chat/entity/Chat.java
  src/main/java/com/metanet/metabus/chat/entity/Room.java
  src/main/java/com/metanet/metabus/chat/service/ChatService.java
  src/test/java/com/metanet/metabus/board/controller/BoardControllerTest.java
  src/test/java/com/metanet/metabus/board/service/BoardServiceTest.java
  src/test/java/com/metanet/metabus/chat/controller/ChatControllerTest.java
  src/test/java/com/metanet/metabus/chat/controller/RoomControllerTest.java
  src/test/java/com/metanet/metabus/chat/service/ChatServiceTest.java
Labels: InProgress

#64 Feature/metabus 54
  src/main/java/com/metanet/metabus/bus/controller/BusController.java
  src/test/java/com/metanet/metabus/bus/controller/BusControllerTest.java
Labels: Done

#65 멤버 수정
  src/main/java/com/metanet/metabus/member/dto/MemberDto.java
  src/main/java/com/metanet/metabus/member/service/MemberService.java
Labels: Done

#66 [Fix] url 주소 수정
  src/main/resources/templates/bus/bus-payment.html
  src/main/resources/templates/mypage/mypage.html
Labels: Done

#70 프론트 영어 변경
  src/main/java/com/metanet/metabus/member/dto/MemberEditInfoRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberRegisterRequest.java
  src/main/resources/templates/log/check_password.html
  src/main/resources/templates/log/check_password_info.html
  src/main/resources/templates/log/check_password_pwd.html
  src/main/resources/templates/log/edit_info.html
  src/main/resources/templates/log/edit_oauth.html
  src/main/resources/templates/log/edit_password.html
  src/main/resources/templates/log/login.html
  src/main/resources/templates/log/register.html
Labels: Done

#71 영어 -> 한국어 , 채팅방 이름표기 추가
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/chat/service/ChatService.java
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/fragments/header2.html
  src/test/java/com/metanet/metabus/chat/service/ChatServiceTest.java
Labels: InProgress

#72 bus 시간표 조회 페이지, bus 예약 관련 QR api 실제 적용, etc.. & front-end 리모델링
  src/main/resources/static/assets/img/busback.jpg
  src/main/resources/static/assets/img/busfront.jpg
  src/main/resources/static/assets/img/whiteqr.png
  src/main/resources/static/css/style-board.css
  src/main/resources/templates/bus/bus-payment.html
  src/main/resources/templates/bus/bus-reservation-table.html
  src/main/resources/templates/bus/bus-time-table.html
  src/main/resources/templates/bus/receipt.html
  src/main/resources/templates/mypage/mypage.html
Labels: InProgress

#73 배포
  src/main/java/com/metanet/metabus/bus/entity/Reservation.java
  src/main/java/com/metanet/metabus/bus/service/ReservationService.java
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/chat/service/ChatService.java
  src/main/java/com/metanet/metabus/common/exception/ErrorCode.java
  src/main/java/com/metanet/metabus/common/exception/bad_request/BadPaymentException.java
  src/main/java/com/metanet/metabus/member/dto/MemberEditInfoRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberRegisterRequest.java
  src/main/java/com/metanet/metabus/mileage/service/MileageService.java
  src/main/java/com/metanet/metabus/scheduler/QuartzConfig.java
  src/main/resources/static/assets/img/busback.jpg
  src/main/resources/static/assets/img/busfront.jpg
  src/main/resources/static/assets/img/whiteqr.png
  src/main/resources/static/css/style-board.css
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/bus/bus-payment.html
  src/main/resources/templates/bus/bus-reservation-table.html
  src/main/resources/templates/bus/bus-time-table.html
  src/main/resources/templates/bus/receipt.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/fragments/header2.html
  src/main/resources/templates/log/check_password.html
  src/main/resources/templates/log/check_password_info.html
  src/main/resources/templates/log/check_password_pwd.html
  src/main/resources/templates/log/edit_info.html
  src/main/resources/templates/log/edit_oauth.html
  src/main/resources/templates/log/edit_password.html
  src/main/resources/templates/log/login.html
  src/main/resources/templates/log/register.html
  src/main/resources/templates/mypage/mypage.html
  src/test/java/com/metanet/metabus/board/controller/BoardControllerTest.java
  src/test/java/com/metanet/metabus/bus/controller/BusControllerTest.java
  src/test/java/com/metanet/metabus/bus/service/ReservationServiceTest.java
  src/test/java/com/metanet/metabus/chat/controller/RoomControllerTest.java
  src/test/java/com/metanet/metabus/chat/service/ChatServiceTest.java
  src/test/java/com/metanet/metabus/member/controller/MemberControllerTest.java
  src/test/java/com/metanet/metabus/member/service/MemberServiceTest.java
Labels: Done

#76 전체적인 UI 수정 작업, etc.. (front-end 리모델링)
  src/main/resources/static/assets/img/busAni2-mobile.gif
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/bus/bus-payment.html
  src/main/resources/templates/bus/bus-reservation-table.html
  src/main/resources/templates/bus/bus-time-table.html
  src/main/resources/templates/bus/receipt.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/header2.html
  src/main/resources/templates/layout/default_layout.html
  src/main/resources/templates/main/index.html
  src/main/resources/templates/mypage/mypage.html
Labels: InProgress

#79 비밀번호 확인 칸 생성
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/main/java/com/metanet/metabus/member/service/MemberService.java
  src/main/java/com/metanet/metabus/oauth/CustomOauth2UserService.java
  src/main/resources/templates/log/check_password_delete.html
  src/main/resources/templates/log/check_password_info.html
  src/main/resources/templates/log/check_password_pwd.html
  src/main/resources/templates/log/edit_oauth.html
  src/main/resources/templates/log/edit_password.html
  src/main/resources/templates/log/password.html
  src/main/resources/templates/log/register.html
  src/main/resources/templates/mypage/mypage.html
Labels: Done

#77 room, board 페이지 페이징 기능 수정 및 room css제거
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/chat/room.html
Labels: InProgress

#80 roomlist 뒤집기
  src/main/java/com/metanet/metabus/chat/component/RoomCleanupScheduler.java
  src/main/java/com/metanet/metabus/chat/repository/RoomRepository.java
  src/main/java/com/metanet/metabus/chat/service/ChatService.java
  src/test/java/com/metanet/metabus/chat/service/ChatServiceTest.java
Labels: InProgress

#81 파비콘 수정 & 이미지 클릭시 홈으로
  src/main/resources/static/assets/img/META_Logo-removebg.png
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/log/check_password_delete.html
  src/main/resources/templates/log/check_password_info.html
  src/main/resources/templates/log/check_password_pwd.html
  src/main/resources/templates/log/edit_info.html
  src/main/resources/templates/log/edit_oauth.html
  src/main/resources/templates/log/edit_password.html
  src/main/resources/templates/log/login.html
  src/main/resources/templates/log/register.html
Labels: Done

#82 테스트 코드 작성
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/test/java/com/metanet/metabus/member/controller/MemberControllerTest.java
  src/test/java/com/metanet/metabus/member/service/MemberServiceTest.java
Labels: Done

#83 전체적인 UI 수정 작업, etc.. (front-end 리모델링)
  src/main/resources/static/css/styles.css
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/bus/bus-cancel.html
  src/main/resources/templates/bus/bus-reservation-table.html
  src/main/resources/templates/bus/receipt.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/header2.html
  src/main/resources/templates/main/index.html
Labels: InProgress

#85 게시판 규칙 지정하기
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/board/boardmodify.html
  src/main/resources/templates/board/boardview.html
  src/main/resources/templates/board/boardwrite.html
Labels: InProgress

#87 프론트 에러상황 처리 기능 추가
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/main/java/com/metanet/metabus/member/dto/MemberRegisterRequest.java
  src/main/java/com/metanet/metabus/member/service/MemberService.java
  src/main/resources/templates/log/check_password_delete.html
  src/main/resources/templates/log/check_password_info.html
  src/main/resources/templates/log/check_password_pwd.html
  src/main/resources/templates/log/edit_info.html
  src/main/resources/templates/log/edit_oauth.html
  src/main/resources/templates/log/edit_password.html
  src/main/resources/templates/log/register.html
Labels: Done

#88 테스트 코드 수정
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/test/java/com/metanet/metabus/member/controller/MemberControllerTest.java
  src/test/java/com/metanet/metabus/member/service/MemberServiceTest.java
Labels: Done

#89 비밀번호 valid 수정
  src/main/java/com/metanet/metabus/member/dto/MemberLoginRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberOAuthRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberPasswordRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberRegisterRequest.java
Labels: Done

#92 이메일 인증 추가
  src/main/resources/templates/log/register.html
Labels: Done

#94 [Fix] 버그 수정
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/main/java/com/metanet/metabus/member/service/MemberService.java
  src/main/resources/templates/log/login.html
  src/main/resources/templates/log/register.html
  src/test/java/com/metanet/metabus/member/controller/MemberControllerTest.java
Labels: Done

#96 관리자 페이지 기본 UI 제작
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/main/resources/templates/mypage/admin.html
  src/main/resources/templates/mypage/mypage.html
Labels: InProgress

#98 room 및 board ui 수정
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/java/com/metanet/metabus/board/dto/LostBoardDto.java
  src/main/java/com/metanet/metabus/board/entity/LostBoard.java
  src/main/java/com/metanet/metabus/board/service/BoardService.java
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/chat/entity/Room.java
  src/main/java/com/metanet/metabus/chat/repository/RoomRepository.java
  src/main/java/com/metanet/metabus/chat/service/ChatService.java
  src/main/java/com/metanet/metabus/member/entity/Member.java
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/board/boardview.html
  src/main/resources/templates/board/boardwrite.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/fragments/header2.html
  src/test/java/com/metanet/metabus/chat/service/ChatServiceTest.java
Labels: InProgress

#99 관리자 페이지 추가
  src/main/java/com/metanet/metabus/bus/dto/BusPopularRoutesRequest.java
  src/main/java/com/metanet/metabus/bus/dto/ReservationStatusRequest.java
  src/main/java/com/metanet/metabus/bus/repository/ReservationRepository.java
  src/main/java/com/metanet/metabus/member/controller/AdminController.java
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/main/java/com/metanet/metabus/member/dto/MemberInfoRequest.java
  src/main/java/com/metanet/metabus/member/service/AdminService.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/mypage/admin.html
Labels: Done

#100 게시판 보기 수정
  src/main/resources/templates/board/boardview.html
  src/main/resources/templates/board/boardwrite.html
Labels: InProgress

#101 배포
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/java/com/metanet/metabus/board/dto/LostBoardDto.java
  src/main/java/com/metanet/metabus/board/entity/LostBoard.java
  src/main/java/com/metanet/metabus/board/service/BoardService.java
  src/main/java/com/metanet/metabus/bus/dto/BusPopularRoutesRequest.java
  src/main/java/com/metanet/metabus/bus/dto/ReservationStatusRequest.java
  src/main/java/com/metanet/metabus/bus/repository/ReservationRepository.java
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/chat/entity/Room.java
  src/main/java/com/metanet/metabus/chat/repository/RoomRepository.java
  src/main/java/com/metanet/metabus/chat/service/ChatService.java
  src/main/java/com/metanet/metabus/member/controller/AdminController.java
  src/main/java/com/metanet/metabus/member/controller/MemberController.java
  src/main/java/com/metanet/metabus/member/dto/MemberEditInfoRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberInfoRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberOAuthRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberRegisterRequest.java
  src/main/java/com/metanet/metabus/member/entity/Member.java
  src/main/java/com/metanet/metabus/member/service/AdminService.java
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/board/boardview.html
  src/main/resources/templates/board/boardwrite.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/header2.html
  src/main/resources/templates/log/register.html
  src/main/resources/templates/mypage/admin.html
  src/main/resources/templates/mypage/mypage.html
  src/test/java/com/metanet/metabus/chat/service/ChatServiceTest.java
Labels: Done

#102 게시판 삭제버튼추가
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/resources/templates/board/boardview.html
Labels: InProgress

#103 테스트 코드 수정
  src/test/java/com/metanet/metabus/member/controller/MemberControllerTest.java
  src/test/java/com/metanet/metabus/member/service/MemberServiceTest.java
Labels: Done

#104 admin 테스트코드 작성
  src/main/java/com/metanet/metabus/common/BaseEntity.java
  src/main/java/com/metanet/metabus/member/service/AdminService.java
  src/test/java/com/metanet/metabus/member/controller/AdminControllerTest.java
  src/test/java/com/metanet/metabus/member/service/AdminServiceTest.java
Labels: InProgress

#106 배포
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/java/com/metanet/metabus/bus/controller/BusController.java
  src/main/java/com/metanet/metabus/bus/controller/BusRestController.java
  src/main/java/com/metanet/metabus/bus/dto/ReservationResponse.java
  src/main/java/com/metanet/metabus/bus/entity/Seat.java
  src/main/java/com/metanet/metabus/bus/service/ReservationService.java
  src/main/java/com/metanet/metabus/common/BaseEntity.java
  src/main/java/com/metanet/metabus/member/dto/MemberInfoDto.java
  src/main/java/com/metanet/metabus/member/service/AdminService.java
  src/main/java/com/metanet/metabus/mileage/controller/MileageController.java
  src/main/resources/templates/board/boardview.html
  src/main/resources/templates/log/check_password_delete.html
  src/main/resources/templates/log/check_password_info.html
  src/main/resources/templates/log/check_password_pwd.html
  src/test/java/com/metanet/metabus/bus/controller/BusControllerTest.java
  src/test/java/com/metanet/metabus/bus/controller/BusRestControllerTest.java
  src/test/java/com/metanet/metabus/bus/service/ReservationServiceTest.java
  src/test/java/com/metanet/metabus/member/controller/AdminControllerTest.java
  src/test/java/com/metanet/metabus/member/controller/MemberControllerTest.java
  src/test/java/com/metanet/metabus/member/service/AdminServiceTest.java
  src/test/java/com/metanet/metabus/member/service/MemberServiceTest.java
  src/test/java/com/metanet/metabus/mileage/controller/MileageControllerTest.java
Labels: Done

#107 [Feat] 게시판보기 에러처리
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/test/java/com/metanet/metabus/board/controller/BoardControllerTest.java
Labels: InProgress

#108 전체적인 UI 마무리 작업
  src/main/resources/static/assets/img/notice-time-table.png
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/board/boardview.html
  src/main/resources/templates/bus/bus-cancel.html
  src/main/resources/templates/bus/bus-payment.html
  src/main/resources/templates/bus/bus-reservation-table.html
  src/main/resources/templates/bus/bus-time-table.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/main/index.html
  src/main/resources/templates/mypage/mileage-table.html
Labels: InProgress

#109 배포
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/java/com/metanet/metabus/bus/service/PaymentService.java
  src/main/java/com/metanet/metabus/chat/controller/RoomController.java
  src/main/java/com/metanet/metabus/member/dto/MemberEditInfoRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberOAuthRequest.java
  src/main/java/com/metanet/metabus/member/dto/MemberRegisterRequest.java
  src/main/resources/static/assets/img/notice-time-table.png
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/board/boardview.html
  src/main/resources/templates/bus/bus-cancel.html
  src/main/resources/templates/bus/bus-payment.html
  src/main/resources/templates/bus/bus-reservation-table.html
  src/main/resources/templates/bus/bus-time-table.html
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/fragments/header2.html
  src/main/resources/templates/main/index.html
  src/main/resources/templates/mypage/mileage-table.html
  src/test/java/com/metanet/metabus/board/controller/BoardControllerTest.java
  src/test/java/com/metanet/metabus/bus/service/PaymentServiceTest.java
Labels: Done

#110 hotfix
  src/main/resources/templates/bus/bus-time-table.html
  src/main/resources/templates/main/index.html
Labels: Done

#111 재배포
  src/main/resources/templates/bus/bus-payment.html
Labels: Done

#112 재배포
  src/main/resources/templates/bus/bus-payment.html
Labels: Done

#113 재배포
  src/main/resources/templates/bus/bus-payment.html
Labels: Done

#115 [Feat] board 테스트코드추가
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/test/java/com/metanet/metabus/board/controller/BoardControllerTest.java
Labels: InProgress

#117 배포
  src/main/java/com/metanet/metabus/board/controller/BoardController.java
  src/main/java/com/metanet/metabus/bus/entity/Seat.java
  src/main/java/com/metanet/metabus/mileage/service/MileageService.java
  src/main/java/com/metanet/metabus/scheduler/QuartzConfig.java
  src/main/resources/templates/board/boardList.html
  src/main/resources/templates/bus/bus-payment.html
  src/main/resources/templates/chat/room.html
  src/test/java/com/metanet/metabus/board/controller/BoardControllerTest.java
  src/test/java/com/metanet/metabus/mileage/service/MileageServiceTest.java
Labels: Done
